#!/bin/bash

ID=$(id -u)
if [ $ID -ne 0 ]; then
	echo "you should be root user"
	exit 1
fi

LOG=/tmp/logs
CONN_HTTP_URL=http://redrockdigimark.com/apachemirror/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.42-src.tar.gz
CONN_TAR_FILE=$(echo "$CONN_HTTP_URL" | cut -d / -f8)  
CONN_SRC_FILE=$(echo "$CONN_TAR_FILE" | sed -e 's/.tar.gz//g')

TOMCAT_HTTP_URL=http://redrockdigimark.com/apachemirror/tomcat/tomcat-9/v9.0.7/bin/apache-tomcat-9.0.7.tar.gz
TOMCAT_TAR_FILE=$(echo "$TOMCAT_HTTP_URL" | awk -F / '{ print $NF }')
TOMCAT_SRC_FILE=$(echo "$TOMCAT_TAR_FILE" | sed -e 's/.tar.gz//g')

TOMCAT_MYSQL_URL=https://github.com/devops2k18/DevOpsDecember/raw/master/APPSTACK/mysql-connector-java-5.1.40.jar
TOMCAT_MYSQL_JAR=$(echo "$TOMCAT_MYSQL_URL" | awk -F / '{ print $NF }')
STUDENT_WAR_URL=https://github.com/devops2k18/DevOpsDecember/raw/master/APPSTACK/student.war 


G="\e[32m"
R="\e[31m"
N="\e[0m"
Y="\e[33m"



VALIDATE ()
{
if [ $1 -eq 0 ]; then
echo -e "$2 $G success $N"
else
echo -e "$2 $R failed $N"
exit 2
fi
}

SKIP ()
{
echo -e "$1 $Y skipping $N"
}

# Webserver installation

yum install httpd -y &>>$LOG
VALIDATE $? "installaing httpd" 



systemctl start httpd &>>$LOG
VALIDATE $? "starting httpd"



systemctl status httpd &>>$LOG
VALIDATE $? "status httpd"

if [ -f /opt/$CONN_TAR_FILE ]; then
SKIP "downlaoding modjk"
else
wget $CONN_HTTP_URL -O /opt/$CONN_TAR_FILE &>>$LOG

VALIDATE $? "downloading modjk"
fi

cd /opt

if [ -d /opt/$CONN_SRC_FILE ]; then
SKIP "extracting modjk"
else
tar xf $CONN_TAR_FILE &>>$LOG
VALIDATE $? "extract modjk file"
fi


cd $CONN_SRC_FILE/native &>>$LOG
VALIDATE $? "change the location to native"



yum install gcc httpd-devel -y &>>$LOG
VALIDATE $? "installing gcc and httpd-devel"


if [ -f /etc/httpd/modules/mod_jk.so ]; then
SKIP "compiling modjk"
else
./configure --with-apxs=/bin/apxs &>>$LOG && make clean &>>$LOG && make &>>$LOG && make install &>>$LOG
VALIDATE $? "compiling modjk"
fi

if [ -f /etc/httpd/conf.d/modjk.conf ]; then
SKIP " creating modjk.conf"
else
cd /etc/httpd/conf.d
echo 'LoadModule jk_module modules/mod_jk.so
JkWorkersFile conf.d/workers.properties
JkLogFile logs/mod_jk.log
JkLogLevel info
JkLogStampFormat "[%a %b %d %H:%M:%S %Y]"
JkOptions +ForwardKeySize +ForwardURICompat -ForwardDirectories
JkRequestLogFormat "%w %V %T"
JkMount /student tomcatA
JkMount /student/* tomcatA' > modjk.conf
VALIDATE $? "creating modjk.conf and insert the data"
fi


if [ -f /etc/httpd/conf.d/workers.properties ]; then
SKIP "creating workers.properties file"
else
echo '### Define workers
worker.list=tomcatA
### Set properties
worker.tomcatA.type=ajp13
worker.tomcatA.host=localhost
worker.tomcatA.port=8009' > workers.properties
VALIDATE $? "creating workers.properties and insert the data"
fi


systemctl  restart  httpd &>>$LOG

VALIDATE $? "restarting the httpd server"
yum install java -y &>>$LOG
VALIDATE $? "installaing java"

#Tomcat server installation

if [ -d /tomcat ]; then
SKIP "directory created"
else
mkdir /tomcat
VALIDATE $? "creating tomcat directory"
fi

wget $TOMCAT_HTTP_URL -O /tomcat/$TOMCAT_TAR_FILE &>>$LOG
if [ -f /tomcat/$TOMCAT_TAR_FILE ]; then
SKIP "downlaoding tomcat"
else 
wget $TOMCAT_HTTP_URL -O /tomcat/$TOMCAT_TAR_FILE &>>$LOG
VALIDATE $? "installing appserver"
fi


cd /tomcat
if [ -d /tomcat/$TOMCAT_SRC_FILE ]; then
SKIP "extracting tomcat"
else
tar -xf $TOMCAT_TAR_FILE &>>$LOG
VALIDATE $? "extracting the appserver"
fi

cd $TOMCAT_SRC_FILE/webapps
if [ -f /tomcat/$TOMCAT_SRC_FILE/webapps/student.war ]; then
SKIP "downloading student.war file"
else 
wget $STUDENT_WAR_URL &>>$LOG
VALIDATE $? "change the location to apache and installaing student.war file"
fi

if [ -f /tomcat/$TOMCAT_SRC_FILE/lib/$TOMCAT_MYSQL_JAR ]; then
SKIP "downlaoding mysql-connector"
else
cd /tomcat/$TOMCAT_SRC_FILE/lib/
wget $TOMCAT_MYSQL_URL &>>$LOG
VALIDATE $? "location change to lib and installaing mysql-connector"
fi


cd /tomcat/$TOMCAT_SRC_FILE/conf &>>$LOG

sed -i -e '/TestDB/ d' context.xml

sed -i -e '$ i <Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource" maxTotal="100" maxIdle="30" maxWaitMillis="10000" username="student" password="student@1" driverClassName="com.mysql.jdbc.Driver" url="jdbc:mysql://localhost:3306/studentapp"/>' context.xml
			   
VALIDATE $? "configuring context.xml file"


# Database installation

yum install mariadb mariadb-server -y &>>$LOG

VALIDATE $? "installaing mariadb"

systemctl restart mariadb &>>$LOG

VALIDATE $? "starting mariadb"

echo "create database if not exists studentapp;
use studentapp;
CREATE TABLE if not exists Students(student_id INT NOT NULL AUTO_INCREMENT,
	student_name VARCHAR(100) NOT NULL,
    student_addr VARCHAR(100) NOT NULL,
	student_age VARCHAR(3) NOT NULL,
	student_qual VARCHAR(20) NOT NULL,
	student_percent VARCHAR(10) NOT NULL,
	student_year_passed VARCHAR(10) NOT NULL,
	PRIMARY KEY (student_id)
);
grant all privileges on studentapp.* to 'student'@'localhost' identified by 'student@1';" > /tmp/student.sql


mysql < /tmp/student.sql

VALIDATE $? "creating Database"



cd /tomcat/$TOMCAT_SRC_FILE/bin

sh shutdown.sh &>>$LOG

sh startup.sh &>>$LOG

VALIDATE $? "restarting tomcat server"
